# Generated by Django 4.2.9 on 2024-02-29 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todoitem_finished_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
